/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace MessageProtocol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TaskModel : TBase
  {
    private string _clientId;
    private string _projectId;
    private string _taskId;

    public string ClientId
    {
      get
      {
        return _clientId;
      }
      set
      {
        __isset.clientId = true;
        this._clientId = value;
      }
    }

    public string ProjectId
    {
      get
      {
        return _projectId;
      }
      set
      {
        __isset.projectId = true;
        this._projectId = value;
      }
    }

    public string TaskId
    {
      get
      {
        return _taskId;
      }
      set
      {
        __isset.taskId = true;
        this._taskId = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool clientId;
      public bool projectId;
      public bool taskId;
    }

    public TaskModel() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                ClientId = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                ProjectId = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                TaskId = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TaskModel");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (ClientId != null && __isset.clientId) {
          field.Name = "clientId";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(ClientId);
          oprot.WriteFieldEnd();
        }
        if (ProjectId != null && __isset.projectId) {
          field.Name = "projectId";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(ProjectId);
          oprot.WriteFieldEnd();
        }
        if (TaskId != null && __isset.taskId) {
          field.Name = "taskId";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(TaskId);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TaskModel(");
      bool __first = true;
      if (ClientId != null && __isset.clientId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ClientId: ");
        __sb.Append(ClientId);
      }
      if (ProjectId != null && __isset.projectId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ProjectId: ");
        __sb.Append(ProjectId);
      }
      if (TaskId != null && __isset.taskId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TaskId: ");
        __sb.Append(TaskId);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
